version: '3.3'

networks:
  api-net:
    driver: bridge

volumes:
  mongo_data:
  redis_data:


services:
  api:
    container_name: codechat_api
    image: codechat/api:v1.2.5
    restart: unless-stopped
    ports:
      - 8083:8083
    volumes:
      - ./instances:/codechat/instances
      - ./src/env.yml:/codechat/src/env.yml
    command: [ 'node', './src/main.js' ]
    networks:
      - api-net

  mongodb:
    container_name: mongodb
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mysupersecretpassword
    networks:
      - api-net

  cache:
    image: redis:7
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - api-net
